version: '2'

services:
  postgresql:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: integracao_cnpj_schema
    networks:
      - commons-api

  app:
    build:
      context: ./consulta-cnpj
    container_name: app
    ports:
      - 8081:8081
    environment:
      - JDBC_URL=jdbc:postgresql://postgresql:5432/integracao_cnpj_schema?createDatabaseIfNotExist=true
      - JDBC_USER=postgres
      - JDBC_PASS=postgres
    depends_on:
      - postgresql
    networks:
      - commons-api
      
  integracao-cnpj:
    build:
      context: ./integracao-cnpj
    ports:
      - "8080:8080"
    depends_on:
      - app
    networks:
      - commons-api

networks:
  commons-api:
    driver: bridge