CREATE TABLE cliente (
    ID_CLIENTE SERIAL PRIMARY KEY,
    RAZAO_SOCIAL VARCHAR(255),
    CIDADE VARCHAR(255),
    SITUACAO_CADASTRAL VARCHAR(255),
    DATA_CADASTRO TIMESTAMP,
    ENDERECO VARCHAR(255),
    TELEFONE VARCHAR(255)
);